# Generated by Django 4.2.1 on 2023-07-06 06:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geister", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gamestate",
            old_name="game_state",
            new_name="table_state",
        ),
    ]
