# Generated by Django 4.2.1 on 2023-07-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geister", "0002_rename_game_state_gamestate_table_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamestate",
            name="table_state",
        ),
        migrations.AddField(
            model_name="gamestate",
            name="players",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="gamestate",
            name="table",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="gamestate",
            name="turn",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gamestate",
            name="winner",
            field=models.CharField(default="", max_length=255),
        ),
    ]
